server:
  port: ${SERVER_PORT:8000}

spring:
  main:
    web:
      application:
        type: reactive
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}
  application:
    name: apigateway-service
  cloud:
    gateway:
      default-filters:
        - name: GlobalFilter
          args:
            baseMessage: Spring Cloud Gateway Global Filter
            preLogger: true
            postLogger: true
      routes:
        - id: first-service
          # uri: http://43.201.25.43:8081/
          uri: lb://USER-SERVICE-FIRST
          predicates:
            - Path=/first-service/**
          filters:
            #- AddRequestHeader=first-request, first-Request-header2
            #- AddResponseHeader=first-request, first-Response-header2
            - CustomFilter
        - id: second-service
          # uri: http://localhost:8080/
          uri: lb://USER-SERVICE-SECOND
          predicates:
            - Path=/second-service/**
          filters:
            #- AddRequestHeader=second-request, second-Request-header2
            #- AddResponseHeader=second-request, second-Response-header2
            - CustomFilter
            - name: CustomLoggingFilter
              args:
                baseMessage: Spring Cloud Gateway Custom Logging Filter
                preLogger: true
                postLogger: true